blueprint:
  name: Ikea remote via zigbee2mqtt
  description: "Controls a light with a switch given by ENTITY. \n\nShort Button press will toggle light for both Buttons (helpfull in darkness) \n\n Mode set to restart is mandatory for stop after long press to work."
  domain: automation
  input:
    source_switch_e1743_action:
      name: Tradfri E1743 Switch
      description: The switch-action which triggers this automation.
      selector:
        entity:
          filter:
            - integration: mqtt
              domain: sensor
    remote_name:
      name: (Zigbee2MQTT) Remote Name
      description: The name of the controller (e.g. IKEA Rodret). **_Choose if you are using Zigbee2MQTT._**
      default: ""
    target_light:
      name: Target Light
      description: the light you want to control.
      selector:
        target:
    on_double_press:
      name: On - Double press event
      description:
        Choose whether or not to expose the virtual **double press** event
        for the **on** button. Turn this on if you are providing an action for the **on**
        button double press event.
      default: false
      selector:
        boolean: {}
    on_double_press_action:
      name: On - Double press action
      description:
        Choose action(s) to run when pressing the **on** button twice in **Helper - Double press
        delay** interval. **On - Double press event** must be exposed.
      default: []
      selector:
        action: {}
    off_double_press:
      name: Off - Double press event
      description:
        Choose whether or not to expose the virtual **double press** event
        for the **off** button. Turn this on if you are providing an action for the **off**
        button double press event.
      default: false
      selector:
        boolean: {}
    off_double_press_action:
      name: Off - Double press action
      description:
        Choose action(s) to run when pressing the **off** button twice in **Helper - Double press
        delay** interval. **Off - Double press event** must be exposed.
      default: []
      selector:
        action: {}
    helper_double_press_delay:
      name: Helper - Double press delay
      description:
        Max delay between the first and the second button press for the
        **Double press events**. Provide a value only if you are using a double press action.
        Increase this value if you notice that the double press action is not triggered
        properly.
      default: 400
      selector:
        number:
          unit_of_measurement: milliseconds
          min: 100.0
          max: 5000.0
          step: 10.0
          mode: slider
    min_brightness:
      name: (Optional) Light minimum brightness
      description: The minimum brightness the light can be set with this automation.
      default: 1
      selector:
        number:
          min: 1
          max: 255
          step: 1
          unit_of_measurement: brightness
          mode: slider
    max_brightness:
      name: (Optional) Light maximum brightness
      description: The maximum brightness the light can be set with this automation.
      default: 255
      selector:
        number:
          min: 0
          max: 255
          step: 1
          unit_of_measurement: brightness
          mode: slider
alias: Ikea remote via zigbee2mqtt
description: ""
trigger:
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: "on"
    to: "on"
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: "off"
    to: "off"
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: arrow_left_click
    to: arrow_left_click
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: arrow_right_click
    to: arrow_right_click
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: brightness_move_up
    to: brightness_move_up
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: brightness_move_down
    to: brightness_move_down
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: arrow_left_hold
    to: arrow_left_hold
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: arrow_right_hold
    to: arrow_right_hold
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: brightness_stop
    to: brightness_stop
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: arrow_left_release
    to: arrow_left_release
  - platform: state
    entity_id: !input source_switch_e1743_action
    id: arrow_right_release
    to: arrow_right_release  
condition: []
action:
  - variables:
      on_double_press: !input on_double_press
      off_double_press: !input off_double_press
      z2m_controller: !input remote_name
      area: !input target_light
      lights: "{{ 
                expand(states.light) 
                |selectattr('state', 'eq', 'on')
                |selectattr('entity_id', 'in', area_entities(area.area_id))
                |sort(attribute='attributes.brightness', reverse=True)
                |map(attribute='entity_id') |first 
              }}"
  - choose:
      - conditions:
          - condition: trigger
            id:
              - "on"
        sequence:
          - if:
              - condition: template
                value_template: "{{ on_double_press }}"
            then:
              - wait_for_trigger:
                  - platform: mqtt
                    topic: "{{ 'zigbee2mqtt/' ~ z2m_controller ~ '/action' }}"
                    payload: "on"
                timeout:
                  milliseconds: !input helper_double_press_delay
                continue_on_timeout: true
              - if:
                  - condition: template
                    value_template: "{{ wait.trigger.idx is defined }}"
                then: !input on_double_press_action
                else: 
                  - service: light.turn_on
                    data: {}
                    target: !input target_light
            else: 
              - service: light.turn_on
                data: {}
                target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - "off"
        sequence:
          - if:
              - condition: template
                value_template: "{{ off_double_press }}"
            then:
              - wait_for_trigger:
                  - platform: mqtt
                    topic: "{{ 'zigbee2mqtt/' ~ z2m_controller ~ '/action' }}"
                    payload: "off"
                timeout:
                  milliseconds: !input helper_double_press_delay
                continue_on_timeout: true
              - if:
                  - condition: template
                    value_template: "{{ wait.trigger.idx is defined }}"
                then: !input off_double_press_action
                else: 
                  - service: light.turn_off
                    data: {}
                    target: !input target_light
            else: 
              - service: light.turn_off
                data: {}
                target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - brightness_move_up
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: 5
                    transition: 0.2
                  target: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
      - conditions:
          - condition: trigger
            id:
              - brightness_move_down
        sequence:
          - repeat:
              count: 50
              sequence:
                - if:
                    - condition: template
                      value_template: "{{ state_attr(lights, 'brightness') > 10 }}"
                  then:
                    - service: light.turn_on
                      data:
                        brightness_step_pct: -5
                        transition: 0.2
                      target: !input target_light
                - delay:
                    milliseconds: 200
mode: restart
