blueprint:
  name: Ikea remote via zigbee2mqtt
  description: "Controls a light with a switch given by ENTITY. \n\nShort Button press will toggle light for both Buttons (helpfull in darkness) \n\n Mode set to restart is mandatory for stop after long press to work."
  domain: automation
  input:
    remote_device:
      name: Tradfri E1743 Switch
      description: The switch-action which triggers this automation.
      selector:
        device:
    lights:
      name: lights
      description: the lights you want to control.
      selector:
        target:
alias: Ikea remote via zigbee2mqtt
description: ""
trigger:
  - domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: brightness_move_up
    trigger: device
    id: brightness_move_up
  - domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: brightness_move_down
    trigger: device
    id: brightness_move_down
  - domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: arrow_left_hold
    trigger: device
    id: arrow_left_hold
  - domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: arrow_right_hold
    trigger: device
    id: arrow_right_hold
  - domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: brightness_stop
    trigger: device
    id: brightness_stop
  - domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: arrow_left_release
    trigger: device
    id: arrow_left_release
  - domain: mqtt
    device_id: !input remote_device
    type: action
    subtype: arrow_right_release
    trigger: device
    id: arrow_right_release
condition: []
action:
  - variables:
      lights: !input lights
  - choose:
      - conditions:
          - condition: trigger
            id:
              - brightness_move_up
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: 5
                    transition: 0.2
                  target: 
                    entity_id: >
                      {{ expand('!input lights') | selectattr('state', 'eq', 'on')
                        | map(attribute='entity_id') | list }}
                - delay:
                    milliseconds: 200
              count: 50
      - conditions:
          - condition: trigger
            id:
              - brightness_move_down
        sequence:
          - repeat:
              count: 50
              sequence:
                - data:
                    brightness_step_pct: -5
                    transition: 0.2
                  target:
                    entity_id: |
                      {{ expand('!input lights') | selectattr('state', 'eq', 'on') 
                        | selectattr('attributes.brightness', 'gt', 13)
                        | selectattr('attributes.brightness', 'is_number')
                        | map(attribute='entity_id') | list }}
                  action: light.turn_on
                - delay:
                    milliseconds: 200
mode: restart
